### ISSUE TITLE
Undefined method 'header' for nil:NilClass

### ISSUE THREAD

**Issue by AlectronikForge** [tenderlove/tenderjit#128]
I tried to install and run TenderJIT but it won't start with following error upon rake compile:

`/usr/bin/ruby -I lib misc/build-ruby-internals.rb 65822
/root/GitHub/tenderjit/misc/ruby_internals.rb:310:in `read_dwarf': undefined method `header' for nil:NilClass (NoMethodError)
	from /root/GitHub/tenderjit/misc/ruby_internals.rb:321:in `block in each_compile_unit'
	from /root/GitHub/tenderjit/misc/ruby_internals.rb:318:in `open'
	from /root/GitHub/tenderjit/misc/ruby_internals.rb:318:in `each_compile_unit'
	from /root/GitHub/tenderjit/misc/ruby_internals.rb:114:in `process'
	from /root/GitHub/tenderjit/misc/ruby_internals.rb:381:in `get_internals'
	from misc/build-ruby-internals.rb:435:in `<main>'
rake aborted!`

When commenting that line out, the same error occurs for line 276.
I'd really like to try this project out, so any help is appreciated!

**Comment by tenderlove** [comment]
How did you install Ruby?  TenderJIT needs the DWARF information from the Ruby installation.  It sounds like it might be missing in yours.

Can you paste the output of this:

```
$ ruby -e'puts File.join RbConfig::CONFIG["prefix"], "lib", RbConfig::CONFIG["LIBRUBY_A"]'
```

As well as this:

```
$ dwarfdump $(ruby -e'puts File.join RbConfig::CONFIG["prefix"], "lib", RbConfig::CONFIG["LIBRUBY_A"]') | head -15
```

Thanks!
