### ISSUE TITLE
String can't be coerced into Integer (TypeError)

### ISSUE THREAD

**Issue by wenderjean** [tenderlove/tenderjit#24]
I'm trying to get my feet wet with tenderjit using my Linux environment with GCC but I'm getting this TypeError from `misc/ruby_internals.rb`, after some investigation I'm guessing that's something related to CLang vs GCC but honestly I'm not sure.

#### Configuration

Ruby `3.1.0-dev`
Architecture ` x86_64 GNU/Linux`

#### Error
```
$ bundle exec rake test
/home/<user>/.asdf/installs/ruby/3.1.0-dev/bin/ruby -I lib misc/build-ruby-internals.rb ca092
/home/<user>/tenderjit/misc/ruby_internals.rb:56:in `+': String can't be coerced into Integer (TypeError)
	from /home/<user>/tenderjit/misc/ruby_internals.rb:56:in `read_instruction_op_types'
	from /home/<user>/tenderjit/misc/ruby_internals.rb:119:in `process'
	from /home/<user>/tenderjit/misc/ruby_internals.rb:367:in `get_internals'
	from misc/build-ruby-internals.rb:431:in `<main>'
rake aborted!
Command failed with status (1): [/home/<user>/.asdf/installs/ruby/3.1...]
/home/<user>/tenderjit/Rakefile:43:in `block in <top (required)>'
/home/<user>/.asdf/installs/ruby/3.1.0-dev/bin/bundle:23:in `load'
/home/<user>/.asdf/installs/ruby/3.1.0-dev/bin/bundle:23:in `<main>'
Tasks: TOP => test => compile => lib/tenderjit/ruby/ca092/constants.rb
(See full trace by running task with --trace)
```
#### Debugging
```ruby
def self.read_instruction_op_types symbol_addresses
  len  = RubyVM::INSTRUCTION_NAMES.length

  map = symbol_addresses.keys.grep(/^y\.\d+/).each do |key|
    insn_map = symbol_addresses.fetch(key)
    l = Fiddle::Pointer.new(insn_map)[0, len * Fiddle::SIZEOF_SHORT].unpack("S#{len}")
    break l if l.first(4) == [0, 1, 4, 7] # probably the right one
  end

  key = symbol_addresses.keys.grep(/^x\.\d+/).first
  op_types = symbol_addresses.fetch(key)

  str_buffer_end = map.last

  # op_types       => 123456789 (Integer)
  # str_buffer_end => y.5       (String)
  while Fiddle::Pointer.new(op_types + str_buffer_end)[0] != 0
    str_buffer_end += 1
  end
  Fiddle::Pointer.new(op_types)[0, str_buffer_end].unpack("Z*" * len)
end
```

@tenderlove Do you have any idea what could be wrong?

**Comment by tenderlove** [comment]
That is quite odd. What does the `map` array look like?  It should be a list of integers, is it not?

**Comment by wenderjean** [comment]
The `map` looks like `["y.1", "y.29", "y.5"]` that's exactly what `symbol_addresses.keys.grep(/^y\.\d+/)` returns. I noticed that the condition for breaking the loop is never satisfied what should explain why `map == symbol_addresses.keys.grep(/^y\.\d+/)`.

**Comment by tenderlove** [comment]
Ah, interesting. What sha of Ruby are you building against?  Also what version of GCC?  If we can't find that array then it should raise an exception.

**Comment by wenderjean** [comment]
@tenderlove  I'm building against `ruby 3.1.0dev (2021-10-03T13:34:45Z master dc9112cf10) [x86_64-linux]` using `asdf` as version manager, my GCC version is 10.3.

**Comment by tenderlove** [comment]
I'm not sure why it can't find that symbol.  Though, I've just merged [this PR](https://github.com/ruby/ruby/pull/4633) which should make it easier to find the symbol regardless of which compiler.  I'll update the code to use the new symbol name.

**Comment by wenderjean** [comment]
Thanks for that @tenderlove, I'll take a look at the PR you mentioned in order to grab more context and keep trying to understand why the condition is never satisfied. I'll give it a try also when you update the code. :)

**Comment by tenderlove** [comment]
@wenderjean thanks!

Just to give a little background, TenderJIT needs to disassemble instruction sequences so it can compile them to machine code.  But it needs to find the length of each instruction.  Instructions are encoded in to an array with the instruction and then any parameters next to it.  For example `[:putobject, 1, :putobject, 2, :opt_plus]`.  Ruby has a table that maps instruction to length (e.g. we need to know the length of `putobject` vs `opt_plus`), and this code is trying to extract that table.

**Comment by tenderlove** [comment]
I *think* #29 will fix this.  Please give it a try and let me know!

**Comment by wenderjean** [comment]
The PR you merged fixed the original issue :)
I'm getting other problems now but I believe they're related to my GCC installation or even my whole environment. I'm investigating further :D

```
Could not open library 'libcapstone.so': libcapstone.so: cannot open shared object file: No such file or directory.
Could not open library 'libcapstone.so.4': libcapstone.so.4: cannot open shared object file: No such file or directory.
Could not open library 'libcapstone.so.3': libcapstone.so.3: cannot open shared object file: No such file or directory
from /home/wenderfreese/.asdf/installs/ruby/3.1.0-dev/lib/ruby/gems/3.1.0/gems/ffi-1.15.4/lib/ffi/library.rb:100:in `map'
	from /home/wenderfreese/.asdf/installs/ruby/3.1.0-dev/lib/ruby/gems/3.1.0/gems/ffi-1.15.4/lib/ffi/library.rb:100:in `ffi_lib'
	from /home/wenderfreese/.asdf/installs/ruby/3.1.0-dev/lib/ruby/gems/3.1.0/gems/crabstone-4.0.3/lib/crabstone/cs_version.rb:53:in `<module:Binding>'
	from /home/wenderfreese/.asdf/installs/ruby/3.1.0-dev/lib/ruby/gems/3.1.0/gems/crabstone-4.0.3/lib/crabstone/cs_version.rb:51:in `<module:Crabstone>'
	from /home/wenderfreese/.asdf/installs/ruby/3.1.0-dev/lib/ruby/gems/3.1.0/gems/crabstone-4.0.3/lib/crabstone/cs_version.rb:8:in `<top (required)>'
	from /home/wenderfreese/.asdf/installs/ruby/3.1.0-dev/lib/ruby/gems/3.1.0/gems/crabstone-4.0.3/lib/crabstone/binding/structs.rb:5:in `require'
	from /home/wenderfreese/.asdf/installs/ruby/3.1.0-dev/lib/ruby/gems/3.1.0/gems/crabstone-4.0.3/lib/crabstone/binding/structs.rb:5:in `<top (required)>'
	from /home/wenderfreese/.asdf/installs/ruby/3.1.0-dev/lib/ruby/gems/3.1.0/gems/crabstone-4.0.3/lib/crabstone/binding.rb:4:in `require'
	from /home/wenderfreese/.asdf/installs/ruby/3.1.0-dev/lib/ruby/gems/3.1.0/gems/crabstone-4.0.3/lib/crabstone/binding.rb:4:in `<top (required)>'
	from /home/wenderfreese/.asdf/installs/ruby/3.1.0-dev/lib/ruby/gems/3.1.0/gems/crabstone-4.0.3/lib/crabstone/disassembler.rb:5:in `require'
	from /home/wenderfreese/.asdf/installs/ruby/3.1.0-dev/lib/ruby/gems/3.1.0/gems/crabstone-4.0.3/lib/crabstone/disassembler.rb:5:in `<top (required)>'
	from /home/wenderfreese/.asdf/installs/ruby/3.1.0-dev/lib/ruby/gems/3.1.0/gems/crabstone-4.0.3/lib/crabstone.rb:11:in `require'
	from /home/wenderfreese/.asdf/installs/ruby/3.1.0-dev/lib/ruby/gems/3.1.0/gems/crabstone-4.0.3/lib/crabstone.rb:11:in `<top (required)>'
	from /home/wenderfreese/Documents/Opensource/tenderjit/test/ruby_internals_test.rb:159:in `require'
	from /home/wenderfreese/Documents/Opensource/tenderjit/test/ruby_internals_test.rb:159:in `<class:RubyInternalsTest>'
	from /home/wenderfreese/Documents/Opensource/tenderjit/test/ruby_internals_test.rb:6:in `<class:TenderJIT>'
	from /home/wenderfreese/Documents/Opensource/tenderjit/test/ruby_internals_test.rb:5:in `<top (required)>'
	from /home/wenderfreese/.asdf/installs/ruby/3.1.0-dev/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/rake_test_loader.rb:21:in `require'
	from /home/wenderfreese/.asdf/installs/ruby/3.1.0-dev/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/rake_test_loader.rb:21:in `block in <main>'
	from /home/wenderfreese/.asdf/installs/ruby/3.1.0-dev/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/rake_test_loader.rb:6:in `select'
	from /home/wenderfreese/.asdf/installs/ruby/3.1.0-dev/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/rake_test_loader.rb:6:in `<main>'

```

**Comment by tenderlove** [comment]
Ah, this is for the crabstone dev dependency.  If you install libcapstone, it should fix it up.  This library is handy for debugging, but I don't think it's actually required to run the tests so I'll remove it as a dev dep.

**Comment by wenderjean** [comment]
Everything working now, thanks for the support :)

**Comment by tenderlove** [comment]
No problem!  Thank you!
