### ISSUE TITLE
Error `fetch': key not found: nil (KeyError)

### ISSUE THREAD

**Issue by edipofederle** [tenderlove/tenderjit#3]
Hi,

I'm exploring this project, and just trying to run the tests with: `rake test`, and I have it:

```
/Users/edipo/workspace/tenderjit/misc/ruby_internals.rb:54:in `fetch': key not found: nil (KeyError)
	from /Users/edipo/workspace/tenderjit/misc/ruby_internals.rb:54:in `read_instruction_op_types'
	from /Users/edipo/workspace/tenderjit/misc/ruby_internals.rb:121:in `process'
	from /Users/edipo/workspace/tenderjit/misc/ruby_internals.rb:369:in `get_internals'
	from misc/build-ruby-internals.rb:431:in `<main>'
rake aborted!
Command failed with status (1): [/Users/edipo/.rvm/rubies/ruby-3.0.0/bin/ru...]
/Users/edipo/workspace/tenderjit/Rakefile:43:in `block in <top (required)>'
/Users/edipo/.rvm/gems/ruby-3.0.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/Users/edipo/.rvm/gems/ruby-3.0.0/bin/ruby_executable_hooks:22:in `eval'
/Users/edipo/.rvm/gems/ruby-3.0.0/bin/ruby_executable_hooks:22:in `<main>'
Tasks: TOP => test => compile => lib/tenderjit/ruby/edeb1/constants.rb
(See full trace by running task with --trace)
```

Looking in the [code](https://github.com/tenderlove/tenderjit/blob/main/misc/ruby_internals.rb#L51) Looks like the regex doesn't match anything in the `symbol_addresses` keys. We are trying to match keys like "x.<more any digit>", this is right? While debugging I see keys like `rb_locale_charmap_index`. `rb_ary_to_ary_m`, etc.

Maybe is a very small thing I'm missing here, so appreciate your time helping me. 

Thx

**Comment by 64kramsystem** [comment]
According to the README, that the project supports Ruby 3.0.2+, so this may be the cause (it fails on my machine on 3.0.0 as well, although with a different error).

**Comment by tenderlove** [comment]
@edipofederle It *might* work on 3.0.0.  Can you tell me how you compiled your Ruby?  It seems like maybe you've compiled with GCC on macOS.

Can you run these commands and paste the output?

```
$ ruby -rrbconfig -e'puts File.join RbConfig::CONFIG["prefix"], "lib", RbConfig::CONFIG["LIBRUBY"]'
$ ruby -rrbconfig -e'p RbConfig::CONFIG["CFLAGS"]'
$ ruby -rrbconfig -e'p RbConfig::CONFIG["CC"]'
```

TenderJIT uses DWARF information to generate structs.  It seems like maybe it's not able to locate the DWARF info.  My guess is that GCC is generating different section headers.  I haven't tested GCC on macOS so I'm doing that now!

**Comment by edipofederle** [comment]
@tenderlove I used `rvm install ruby-3.0.0` (by what I remember).

The outputs in order:
```
/Users/edipo/.rvm/rubies/ruby-3.0.0/lib/libruby.3.0.dylib
-O3 -I/usr/local/opt/libyaml/include -I/usr/local/opt/libksba/include -I/usr/local/opt/readline/include -I/usr/local/opt/zlib/include -I/usr/local/opt/openssl@1.1/include -fno-common -pipe
"gcc -fdeclspec"
```

**Comment by stefannibrasil** [comment]
I successfully installed TenderJIT on my ubuntu machine with `ruby 3.0.1` but not with `ruby 3.0.0`. The only error I got was from not having [capstone installed](https://github.com/tenderlove/tenderjit/blob/main/.github/workflows/ci.yml#L18).

**Comment by edipofederle** [comment]
> I successfully installed TenderJIT on my ubuntu machine with `ruby 3.0.1` but not with `ruby 3.0.0`. The only error I got was from not having [capstone installed](https://github.com/tenderlove/tenderjit/blob/main/.github/workflows/ci.yml#L18).

Nice. On macOS even with `ruby 3.0.1` or `ruby 3.0.2` I still get the the same error.
